name: Build Docker images and upload to ghcr.io
on:
  push:
    branches:
      - main
      - master
    tags:
      - '_**'
  schedule:
    - cron: '37 7 * * 3'
  workflow_dispatch:
jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Install python dateutil
        run: pip3 install python-dateutil
      - name: Check out repository code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        # https://github.com/marketplace/actions/docker-setup-qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        # https://github.com/marketplace/actions/docker-setup-buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        # https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # DockerHub:
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push images
        env:
          DOCKER_ACCOUNT: ghcr.io/${{ github.actor }}
          # DOCKER_PASSWORD is optional, only needed for private repositories
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          # DockerHub:
          # DOCKER_ACCOUNT: ${{ secrets.DOCKERHUB_USERNAME }}
          # DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            set -f
            set -- $(echo "${GITHUB_REF_NAME#_}" | tr ';_' ': ')
            set +f
          else
            set --
          fi
          python3 "$GITHUB_WORKSPACE/.github/bin/docker_build" "$@"
