name: Build Docker images and upload to ghcr.io
on:
  push:
    branches:
      - '**'
    tags:
      - '_**'
  schedule:
    - cron: '37 4 * * 2'
  workflow_dispatch:
jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Install python dateutil
        run: pip3 install --no-cache-dir python-dateutil
      - name: Check out repository code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        # https://github.com/marketplace/actions/docker-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        run: |
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            set -f
            images=($(echo "${GITHUB_REF_NAME#_}" | tr ';_' ': '))
            set +f
            python3 "$GITHUB_WORKSPACE/.github/bin/build" "${images[@]}"
          else
            python3 "$GITHUB_WORKSPACE/.github/bin/build"
          fi
